# Generated by Django 2.2.24 on 2023-04-23 10:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование структуры')),
                ('jdata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON данные')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Оргструктура с преемниками',
                'verbose_name_plural': 'Оргструктуры с преемниками',
            },
        ),
        migrations.CreateModel(
            name='Person_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя сотрудника')),
                ('idperson', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID сотрудника')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото сотрудника')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фото сотрудника',
                'verbose_name_plural': 'Фото сотрудников',
            },
        ),
    ]
