# Generated by Django 2.2.24 on 2023-05-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID предприятия')),
                ('organization_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Полное наименование предприятия')),
                ('organization_short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткое наименование предприятия')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID предприятия')),
                ('department_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID подразделения')),
                ('department_short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткое название подразделения')),
                ('department_full_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Полное название подразделения')),
                ('person_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID сотрудника')),
                ('person_tab_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Табельный номер сотрудника')),
                ('person_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сокращенное имя сотрудника')),
                ('person_fio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Полное имя сотрудника')),
                ('position_short_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое название должности')),
                ('position_full_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Полное название должности')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения работника')),
                ('scientific_degree', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ученая степень')),
                ('personnel_reserve', models.CharField(blank=True, max_length=300, null=True, verbose_name='Управленческий кадровый резерв')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения трудового договора')),
                ('assessment_potential', models.CharField(blank=True, max_length=100, null=True, verbose_name='Оценка потенциала')),
                ('readiness', models.CharField(blank=True, max_length=100, null=True, verbose_name='Оценка готовности')),
                ('mobility', models.CharField(blank=True, max_length=100, null=True, verbose_name='Мобильность сотрудника')),
                ('kpi_3', models.FloatField(blank=True, null=True, verbose_name='КПЭ поза-позапрошлого года')),
                ('kpi_2', models.FloatField(blank=True, null=True, verbose_name='КПЭ позапрошлого года')),
                ('kpi_1', models.FloatField(blank=True, null=True, verbose_name='КПЭ прошлого года')),
                ('profile', models.BooleanField(verbose_name='Наличие профиля преемника')),
                ('profile_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID профиля преемника')),
                ('participationAssessment', models.BooleanField(verbose_name='Наличие профиля преемника')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cотрудник',
                'verbose_name_plural': 'Cотрудники',
            },
        ),
    ]
