# Generated by Django 2.2.24 on 2023-05-18 11:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_organization_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career_structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_successor', models.CharField(blank=True, max_length=300, null=True, verbose_name='ID карты преемников')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование карты преемников')),
                ('jdata_org_structure', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON данные')),
                ('jdata_org_successor', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON данные')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Карта преемниками',
                'verbose_name_plural': 'Карты преемниками',
            },
        ),
        migrations.AlterField(
            model_name='persons',
            name='department_id',
            field=models.CharField(blank=True, help_text='тип string, состоит из [код предприятия]+[код подразделения]', max_length=100, null=True, verbose_name='ID подразделения'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='organization_id',
            field=models.CharField(blank=True, help_text='тип string, содержит код предприятия', max_length=100, null=True, verbose_name='ID предприятия'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='person_id',
            field=models.CharField(blank=True, help_text='тип string, состоит из [код предприятия]+[табельный номер]. Для лиц не являющихся работниками предприятия вместо табельного должен генерироваться другой код', max_length=100, null=True, verbose_name='ID сотрудника'),
        ),
    ]
