# Generated by Django 2.2.24 on 2023-05-19 05:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_auto_20230518_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='participationAssessment',
        ),
        migrations.AddField(
            model_name='persons',
            name='participation_assessment',
            field=models.BooleanField(default=False, verbose_name=' Участвовал в оценочных мероприятиях'),
        ),
        migrations.AlterField(
            model_name='career_structure',
            name='jdata_org_structure',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON данные структуры'),
        ),
        migrations.AlterField(
            model_name='career_structure',
            name='jdata_org_successor',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON данные по преемникам'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='profile',
            field=models.BooleanField(default=False, verbose_name='Наличие профиля преемника'),
        ),
    ]
