# Generated by Django 2.2.24 on 2023-05-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_auto_20230519_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career_structure',
            options={'verbose_name': 'Карта c преемниками', 'verbose_name_plural': 'Карты с преемниками'},
        ),
        migrations.AddField(
            model_name='persons',
            name='organization_name',
            field=models.CharField(blank=True, help_text='тип string, содержит наименование предприятия', max_length=300, null=True, verbose_name='Наименование предприятия'),
        ),
    ]
