# Generated by Django 2.2.24 on 2023-06-02 06:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_auto_20230524_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_structure',
            name='jdata_card_changes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON данные сохранение изменений'),
        ),
    ]
