# Generated by Django 2.2.24 on 2023-06-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_career_structure_jdata_card_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Фото сотрудника'),
        ),
        migrations.AlterField(
            model_name='person_photo',
            name='idperson',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID сотрудника'),
        ),
        migrations.AlterField(
            model_name='person_photo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Фото сотрудника'),
        ),
    ]
