# Generated by Django 2.2.24 on 2023-06-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_auto_20230622_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_structure',
            name='company',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование предприятия'),
        ),
    ]
