# Generated by Django 2.2.24 on 2023-06-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0008_career_structure_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='persons',
            name='person_id_photo',
            field=models.CharField(blank=True, help_text='тип string, MD5 из ФИО в маленьком рогистре.', max_length=100, null=True, verbose_name='ID сотрудника для хранения фото'),
        ),
        migrations.AddField(
            model_name='persons',
            name='personnel_reserve_dop',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Управленческий кадровый резерв (УКР доп)'),
        ),
        migrations.AddField(
            model_name='persons',
            name='position_critical',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Критически важная должность'),
        ),
        migrations.AddField(
            model_name='persons',
            name='protection',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Защищенность'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='personnel_reserve',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Управленческий кадровый резерв (УКР)'),
        ),
    ]
