# Generated by Django 2.2.24 on 2023-07-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0009_auto_20230625_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID должности')),
                ('position_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Полное наименование должности')),
                ('position_short_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Краткое наименование должности')),
                ('organization_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID предприятия')),
                ('protect', models.CharField(blank=True, max_length=100, null=True, verbose_name='Защищенность')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_idmd5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID md5 предприятия'),
        ),
    ]
