# Generated by Django 2.2.24 on 2023-07-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0010_auto_20230705_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='assessment_potential_year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Год Оценки потенциала'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='Фото сотрудника'),
        ),
    ]
