# Generated by Django 2.2.24 on 2023-10-11 07:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0011_auto_20230717_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_structure',
            name='jdata_persons',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON данные о сотрудниках'),
        ),
    ]
