# Generated by Django 2.2.24 on 2023-10-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0012_career_structure_jdata_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_photo',
            name='idphoto',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID фотогрвфии'),
        ),
    ]
