# Generated by Django 2.2.24 on 2023-10-11 10:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0013_person_photo_idphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_structure',
            name='jdata_persons_photos',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON фото сотрудников'),
        ),
    ]
