# Generated by Django 2.2.24 on 2023-11-20 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('career', '0014_career_structure_jdata_persons_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_structure',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='person_photo',
            name='idphoto',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID фотографии'),
        ),
    ]
