# Generated by Django 2.2.24 on 2023-11-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0015_auto_20231120_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_structure',
            name='type_map',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип карты'),
        ),
    ]
