# Generated by Django 2.2.24 on 2023-12-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0016_career_structure_type_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя файла')),
                ('idperson', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID сотрудника')),
                ('profile_file', models.FileField(blank=True, default='', null=True, upload_to='profile', verbose_name='Файл профиля сотрудника')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Файл профиля сотрудника',
                'verbose_name_plural': 'Файлы профилей сотрудников',
            },
        ),
    ]
