# Generated by Django 2.2.24 on 2023-12-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0017_person_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_structure',
            name='id_folder',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='id папки'),
        ),
        migrations.CreateModel(
            name='TreeFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование папки')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='career.TreeFolders')),
            ],
            options={
                'verbose_name': 'Дерево папок',
                'verbose_name_plural': 'Дерево папок',
            },
        ),
    ]
