# Generated by Django 2.2.24 on 2024-01-18 07:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0018_auto_20231227_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_structure',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик (да/нет)'),
        ),
        migrations.AddField(
            model_name='career_structure',
            name='jdata_card_draft',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON данные черновика'),
        ),
        migrations.AlterField(
            model_name='treefolders',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.TreeFolders'),
        ),
    ]
