# Generated by Django 2.2.24 on 2024-01-19 08:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0019_auto_20240118_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_structure',
            name='jdata_card_default',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON данные по умолчани сохраненные из конструктора'),
        ),
    ]
