# Generated by Django 2.2.24 on 2024-02-18 12:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0020_career_structure_jdata_card_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, verbose_name='UID')),
                ('name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('jdata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON данные')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Справочник Подоазделение',
                'verbose_name_plural': 'Справочник Подразделений',
            },
        ),
        migrations.CreateModel(
            name='SOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, verbose_name='UID')),
                ('name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('jdata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON данные')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Справочник Организация',
                'verbose_name_plural': 'Справочник Организаций',
            },
        ),
        migrations.CreateModel(
            name='SPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, verbose_name='UID')),
                ('name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('jdata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON данные')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id_sorganization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.SOrganization')),
            ],
            options={
                'verbose_name': 'Справочник Должность',
                'verbose_name_plural': 'Справочник Доджностей',
            },
        ),
        migrations.CreateModel(
            name='SPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, verbose_name='UID')),
                ('name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('jdata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON данные')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id_sdepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.SDepartment')),
                ('id_sorganization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.SOrganization')),
                ('id_sposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.SPosition')),
            ],
            options={
                'verbose_name': 'Справочник Сотрудник',
                'verbose_name_plural': 'Справочник Сотрудников',
            },
        ),
        migrations.AddField(
            model_name='sdepartment',
            name='id_sorganization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.SOrganization'),
        ),
    ]
