# Generated by Django 2.2.24 on 2024-02-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0021_auto_20240218_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='position_id',
            field=models.CharField(blank=True, help_text='тип string', max_length=100, null=True, verbose_name='ID должности'),
        ),
    ]
