# Generated by Django 2.2.24 on 2024-03-12 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0023_person_profile_jdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sposition',
            options={'verbose_name': 'Справочник Должность', 'verbose_name_plural': 'Справочник Должностей'},
        ),
        migrations.AddField(
            model_name='sposition',
            name='id_sdepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.SDepartment'),
        ),
    ]
